FROM node:lts as builder
# Our base image, Using Node.js LTS

# Set the Current Working Directory inside the container
# and copy Vue.js code to the Working Directory
WORKDIR /app 
COPY webui webui 

WORKDIR /app/webui
RUN npm run build-prod

# Create final container
FROM nginix:stable

### Copy the build output to replace the default Nginx contents.
COPY --from=builder /app/webui/dist /usr/share/nginx/html

