compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableTelemetry: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux

yarnPath: .yarn/releases/yarn-4.6.0.cjs
